services:
  - type: web
    name: chatbot-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python rag_server.py
    envVars:
      - key: PORT
        value: 5000
    plan: free
t